input:
  inproc: handle_account_rpc

pipeline:
  processors:
    - log:
        message: "processing accounts rpc"
    - mapping: |
        root = {"message": "hello from accounts"}

output:
  sync_response: {}

